name: 'Hello World'
description: 'Greet someone'
inputs:
  pat: 
    description: 'sourcecraft.dev Personal Access Token'
    required: true
    default: ''
  telegram-token:
    description: 'telegram bot token'
    required: true
    default: ''
  chat-id:
    description: 'telegram chat ID'
    required: true
    default: ''
  orgslug:
    description: 'orgslug'
    required: true
    default: ''
  reposlug:
    description: 'reposlug'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - name: Setup Go Environment
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.2'
    - run: go run main.go -os ${{ inputs.orgslug }} -rs ${{ inputs.reposlug }} -pt ${{ inputs.pat }} -tt ${{ inputs.telegram-token }} -id ${{ inputs.chat-id }}
    - name: All good
      run: echo "Closing..."
      shell: bash