name: 'sourcecraft-notify'
description: 'hackathon task'
inputs:
  pat: 
    description: 'sourcecraft.dev Personal Access Token'
    required: true
    default: ''
  telegram-token:
    description: 'telegram bot token'
    required: true
    default: ''
  chat-id:
    description: 'telegram chat ID'
    required: true
    default: ''
  orgslug:
    description: 'orgslug'
    required: true
    default: ''
  reposlug:
    description: 'reposlug'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - uses: actions/checkout@v5
    - name: Setup Go Environment
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.2'
    - name: Running notifier
      run: go run main.go -os ${{ inputs.orgslug }} -rs ${{ inputs.reposlug }} -pt ${{ inputs.pat }} -tt ${{ inputs.telegram-token }} -id ${{ inputs.chat-id }}
      shell: bash
    - name: All good
      run: echo "Closing..."
      shell: bash
